[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.4.2"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "engine_benchmark"
harness = false
