[package]
name = "app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "chess"
path = "src/main.rs"

[dependencies]
# Local crates
engine = { path = "../engine" }

# External crates
bevy = { version = "0.13.0", features = ["dynamic_linking"] }
rand = "0.8.5"
